substitutions:
  uart_tx_pin: GPIO4
  uart_rx_pin: GPIO3

packages:
  acr_pa: github://franksch50/senhus-connect-esphome/acr-pa.yaml@27cb153e1e60ce6e5ac11752c38e2f78e0bc9566

dashboard_import:
  package_import_url: github://franksch50/senhus-connect-esphome/acr-pa-v2.yaml@main
  import_full_config: false
